<?php

namespace ContainerVyJ5cAT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2cosYPDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2cosYPD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2cosYPD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AccueilController::accueil' => ['privates', '.service_locator.vqbRAJs', 'get_ServiceLocator_VqbRAJsService', true],
            'App\\Controller\\CorporationsController::delete' => ['privates', '.service_locator.azozVe8', 'get_ServiceLocator_AzozVe8Service', true],
            'App\\Controller\\CorporationsController::edit' => ['privates', '.service_locator.azozVe8', 'get_ServiceLocator_AzozVe8Service', true],
            'App\\Controller\\CorporationsController::index' => ['privates', '.service_locator.cJ7bGcQ', 'get_ServiceLocator_CJ7bGcQService', true],
            'App\\Controller\\CorporationsController::new' => ['privates', '.service_locator.cJ7bGcQ', 'get_ServiceLocator_CJ7bGcQService', true],
            'App\\Controller\\CorporationsController::show' => ['privates', '.service_locator.sQXkyLF', 'get_ServiceLocator_SQXkyLFService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\VilleController::delete' => ['privates', '.service_locator.ugHaBOk', 'get_ServiceLocator_UgHaBOkService', true],
            'App\\Controller\\VilleController::edit' => ['privates', '.service_locator.ugHaBOk', 'get_ServiceLocator_UgHaBOkService', true],
            'App\\Controller\\VilleController::index' => ['privates', '.service_locator.vqbRAJs', 'get_ServiceLocator_VqbRAJsService', true],
            'App\\Controller\\VilleController::new' => ['privates', '.service_locator.vqbRAJs', 'get_ServiceLocator_VqbRAJsService', true],
            'App\\Controller\\VilleController::show' => ['privates', '.service_locator.qzIfI5y', 'get_ServiceLocator_QzIfI5yService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AccueilController:accueil' => ['privates', '.service_locator.vqbRAJs', 'get_ServiceLocator_VqbRAJsService', true],
            'App\\Controller\\CorporationsController:delete' => ['privates', '.service_locator.azozVe8', 'get_ServiceLocator_AzozVe8Service', true],
            'App\\Controller\\CorporationsController:edit' => ['privates', '.service_locator.azozVe8', 'get_ServiceLocator_AzozVe8Service', true],
            'App\\Controller\\CorporationsController:index' => ['privates', '.service_locator.cJ7bGcQ', 'get_ServiceLocator_CJ7bGcQService', true],
            'App\\Controller\\CorporationsController:new' => ['privates', '.service_locator.cJ7bGcQ', 'get_ServiceLocator_CJ7bGcQService', true],
            'App\\Controller\\CorporationsController:show' => ['privates', '.service_locator.sQXkyLF', 'get_ServiceLocator_SQXkyLFService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\VilleController:delete' => ['privates', '.service_locator.ugHaBOk', 'get_ServiceLocator_UgHaBOkService', true],
            'App\\Controller\\VilleController:edit' => ['privates', '.service_locator.ugHaBOk', 'get_ServiceLocator_UgHaBOkService', true],
            'App\\Controller\\VilleController:index' => ['privates', '.service_locator.vqbRAJs', 'get_ServiceLocator_VqbRAJsService', true],
            'App\\Controller\\VilleController:new' => ['privates', '.service_locator.vqbRAJs', 'get_ServiceLocator_VqbRAJsService', true],
            'App\\Controller\\VilleController:show' => ['privates', '.service_locator.qzIfI5y', 'get_ServiceLocator_QzIfI5yService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AccueilController::accueil' => '?',
            'App\\Controller\\CorporationsController::delete' => '?',
            'App\\Controller\\CorporationsController::edit' => '?',
            'App\\Controller\\CorporationsController::index' => '?',
            'App\\Controller\\CorporationsController::new' => '?',
            'App\\Controller\\CorporationsController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\VilleController::delete' => '?',
            'App\\Controller\\VilleController::edit' => '?',
            'App\\Controller\\VilleController::index' => '?',
            'App\\Controller\\VilleController::new' => '?',
            'App\\Controller\\VilleController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AccueilController:accueil' => '?',
            'App\\Controller\\CorporationsController:delete' => '?',
            'App\\Controller\\CorporationsController:edit' => '?',
            'App\\Controller\\CorporationsController:index' => '?',
            'App\\Controller\\CorporationsController:new' => '?',
            'App\\Controller\\CorporationsController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\VilleController:delete' => '?',
            'App\\Controller\\VilleController:edit' => '?',
            'App\\Controller\\VilleController:index' => '?',
            'App\\Controller\\VilleController:new' => '?',
            'App\\Controller\\VilleController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
