<?php

namespace ContainerX5ILNvA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UgHaBOkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ugHaBOk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ugHaBOk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ville' => ['privates', '.errored..service_locator.ugHaBOk.App\\Entity\\Ville', NULL, 'Cannot autowire service ".service_locator.ugHaBOk": it references class "App\\Entity\\Ville" but no such service exists.'],
            'villeRepository' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService', true],
        ], [
            'ville' => 'App\\Entity\\Ville',
            'villeRepository' => 'App\\Repository\\VilleRepository',
        ]);
    }
}
