<?php

namespace ContainerF503wem;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCorporationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.azozVe8.App\Entity\Corporations' shared service.
     *
     * @return \App\Entity\Corporations
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.azozVe8": it references class "App\\Entity\\Corporations" but no such service exists.');
    }
}
