<?php

namespace ContainerZyA5wSO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVille2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ugHaBOk.App\Entity\Ville' shared service.
     *
     * @return \App\Entity\Ville
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ugHaBOk": it references class "App\\Entity\\Ville" but no such service exists.');
    }
}
