<?php

namespace ContainerV6FQOFi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChickenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AhlX4P8.App\Entity\Chicken' shared service.
     *
     * @return \App\Entity\Chicken
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.AhlX4P8": it references class "App\\Entity\\Chicken" but no such service exists.');
    }
}
