<?php

namespace ContainerU4jxbBV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CJ7bGcQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cJ7bGcQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cJ7bGcQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'corporationsRepository' => ['privates', 'App\\Repository\\CorporationsRepository', 'getCorporationsRepositoryService', true],
        ], [
            'corporationsRepository' => 'App\\Repository\\CorporationsRepository',
        ]);
    }
}
