<?php

namespace ContainerU4jxbBV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AhlX4P8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AhlX4P8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AhlX4P8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chicken' => ['privates', '.errored..service_locator.AhlX4P8.App\\Entity\\Chicken', NULL, 'Cannot autowire service ".service_locator.AhlX4P8": it references class "App\\Entity\\Chicken" but no such service exists.'],
        ], [
            'chicken' => 'App\\Entity\\Chicken',
        ]);
    }
}
