<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZyA5wSO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZyA5wSO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZyA5wSO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZyA5wSO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZyA5wSO\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZyA5wSO',
    'container.build_id' => '994cd512',
    'container.build_time' => 1674406929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZyA5wSO');
