<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVyJ5cAT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVyJ5cAT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVyJ5cAT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVyJ5cAT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVyJ5cAT\App_KernelDevDebugContainer([
    'container.build_hash' => 'VyJ5cAT',
    'container.build_id' => '4ba674fc',
    'container.build_time' => 1674412872,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVyJ5cAT');
