<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNXbGPA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNXbGPA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNNXbGPA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNNXbGPA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNNXbGPA\App_KernelDevDebugContainer([
    'container.build_hash' => 'NNXbGPA',
    'container.build_id' => 'c6f535d3',
    'container.build_time' => 1674409081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNXbGPA');
