<?php

namespace ContainerZflUgVZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AzozVe8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.azozVe8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.azozVe8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'corporation' => ['privates', '.errored..service_locator.azozVe8.App\\Entity\\Corporations', NULL, 'Cannot autowire service ".service_locator.azozVe8": it references class "App\\Entity\\Corporations" but no such service exists.'],
            'corporationsRepository' => ['privates', 'App\\Repository\\CorporationsRepository', 'getCorporationsRepositoryService', true],
        ], [
            'corporation' => 'App\\Entity\\Corporations',
            'corporationsRepository' => 'App\\Repository\\CorporationsRepository',
        ]);
    }
}
